name: CI Workflow

on:
  pull_request:
  push:
    branches:
      - f/**
      - p/**
      - next
      - master

jobs:
  lint_build_test:
    name: Lint, Build & Test
    env:
      DB_URL: mongodb://localhost:27017/mgdb-migrator-db
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
